#version: '3.7'    - the attribute `version` is obsolete, it will be ignored

networks:
  currency-service-network:

volumes:
  mysql_data:

services:
  # ----------------------------------------------------------------------------------------------------------------------
  currency-service-mysql-db:
    image: mysql:8.4
    mem_limit: 700m
    networks:
      - currency-service-network
    ports:
      - "3336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Alliswell@1"
      MYSQL_DATABASE: "currency_exchange_service"
      MYSQL_USER: "maniraj"
      MYSQL_PASSWORD: "Alliswell@1"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--protocol=tcp", "-h", "127.0.0.1", "-u", "maniraj", "-pAlliswell@1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# ----------------------------------------------------------------------------------------------------------------------
  naming-server:
    image: dockeraaanm/naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    networks:
      - currency-service-network
    ports:
      - "8761:8761"

# ----------------------------------------------------------------------------------------------------------------------
  zipkin:
    image: openzipkin/zipkin:latest
    mem_limit: 700m
    networks:
      - currency-service-network
    ports:
      - "9411:9411"

  # ----------------------------------------------------------------------------------------------------------------------
  config-server:
    image: dockeraaanm/spring-cloud-config-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    networks:
      - currency-service-network
    ports:
      - "8888:8888"
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/

    depends_on:
      - naming-server

# ----------------------------------------------------------------------------------------------------------------------
  currency-exchange-service:
    image: dockeraaanm/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m  # Version 2.x: Use mem_limit directly under service
    networks:
      - currency-service-network
    ports:
      - "8000:8000"
    environment:
      spring.datasource.url: jdbc:mysql://currency-service-mysql-db:3306/currency_exchange_service
      spring.datasource.username: maniraj
      spring.datasource.password: Alliswell@1
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/

    depends_on:
      - config-server

#  currency-exchange-service:
#    image: dockeraaanm/currency-exchange-service:0.0.1-SNAPSHOT
#    networks:
#      - currency-service-network
#    ports:
#      - "8000:8000"
##    mem_limit: 700m  # Version 2.x: Use mem_limit directly under service
##    deploy:
##      resources:
##        limits:
##          memory: 700m  # Version 3.x: Use deploy.resources.limits.memory
#    environment:
#      SERVER_PORT: "8000"
#      SPRING_APPLICATION_NAME: "currency-exchange-service"
##      SPRING_CONFIG_IMPORT: "optional:configserver:http://localhost:8888"
#      SPRING_CLOUD_CONFIG_PROFILE: "dev"
#      SPRING_SQL_INIT_MODE: "always"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://currency-service-mysql-db:3336/currency_exchange_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
##      SPRING_DATASOURCE_URL: "jdbc:mysql://currency-service-mysql-db:3336/currency_exchange_service"
##      SPRING_DATASOURCE_URL: "jdbc:mysql://currency-service-mysql-db:3336/currency_exchange_service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false"
#      SPRING_DATASOURCE_USERNAME: "maniraj"
#      SPRING_DATASOURCE_PASSWORD: "Alliswell@1"
##      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
##      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.jdbc.Driver"
#      SPRING_JPA_SHOW_SQL: "true"
#      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
#      SPRING_JPA_HIBERNATE_DDL_AUTO: "create-drop"
#      SPRING_JPA_PROPERTIES_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
#      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQLDialect"
#      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
#      RESILIENCE4J_RETRY_INSTANCES_CURRENCY_EXCHANGE_GET_ALL_MAXRETRYATTEMPTS: "5"
#      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
#      LOGGING_PATTERN_LEVEL: "%5p [$${spring.application.name},%X{traceId:-},%X{spanId:-}]"
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://naming-server:8765/eureka"
#      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
#      EUREKA_INSTANCE_IP_ADDRESS: "localhost"
#      EUREKA_INSTANCE_HOSTNAME: "localhost"
#      EUREKA_INSTANCE_INSTANCE_ID: "$${spring.application.name}:$${server.port}"
#    depends_on:
#      currency-service-mysql-db:
#        condition: service_healthy
#
# ----------------------------------------------------------------------------------------------------------------------
  currency-conversion-service:
    image: dockeraaanm/currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    networks:
      - currency-service-network
    ports:
      - "8100:8100"
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/

    depends_on:
      - currency-exchange-service

#      RESILIENCE4J_RETRY_INSTANCES_CURRENCY_CONVERSION_API_MAXATTEMPTS: "5"
#      RESILIENCE4J_RETRY_INSTANCES_CURRENCY_CONVERSION_API_WAITDURATION: "5s"
#      RESILIENCE4J_RETRY_INSTANCES_CURRENCY_CONVERSION_API_ENABLEEXPONENTIALBACKOFF: "true"
#      RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DEFAULT_FAILURERATETHRESHOLD: "90"
#      RESILIENCE4J_RATELIMIT_INSTANCES_DEFAULT_LIMITFORPERIOD: "2"
#      RESILIENCE4J_RATELIMIT_INSTANCES_DEFAULT_LIMITREFRESHPERIOD: "10s"
#      RESILIENCE4J_BULKHEAD_INSTANCES_DEFAULT_MAXCONCURRENTCALLS: "10"
#      SPRING_CONFIG_IMPORT: "optional:configserver:http://localhost:8888"
#      SPRING_CLOUD_CONFIG_PROFILE: "dev"
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://naming-server:8761/eureka"
#      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
#      EUREKA_INSTANCE_IP_ADDRESS: "localhost"
#      EUREKA_INSTANCE_HOSTNAME: "localhost"
#      EUREKA_INSTANCE_INSTANCE_ID: "$${spring.application.name}:$${server.port}"
#      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
#      LOGGING_PATTERN_LEVEL: "%5p [$${spring.application.name},%X{traceId:-},%X{spanId:-}]"



# ----------------------------------------------------------------------------------------------------------------------
  api-gateway:
    image: dockeraaanm/api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    networks:
      - currency-service-network
    ports:
      - "8765:8765"
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/

    depends_on:
      - currency-conversion-service

#      SPRING_APPLICATION_NAME: api-gateway
#      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
#      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID: "true"
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8765/eureka
#      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
#      EUREKA_INSTANCE_IP_ADDRESS: "localhost"
#      EUREKA_INSTANCE_HOSTNAME: "localhost"
#      EUREKA_INSTANCE_INSTANCE_ID: "$${spring.application.name}:$${server.port}"
#      EUREKA_CONFIG_IMPORT: optional:configserver:http://localhost:8888
#      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
#      LOGGING_PATTERN_LEVEL: "%5p [$${spring.application.name},%X{traceId:-},%X{spanId:-}]"





# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------