spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: file:///D:/GitHub/git-localconfig-repo-currency-conversion-services
#          uri: file:///C:/Users/Maniraj/Desktop/currency-conversion-services/git-localconfig-repo-currency-conversion-services
server:
  port: 8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    ip-address: localhost  # or use actual IP
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
