spring:
  application:
    name: limits-service


  profiles:
    active: dev   # Profile changes without this property
  cloud:
    config:
      profile: dev

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8080

limits-service:
  minimum: 2
  maximum: 888